oshliaer/google-apps-script-awesome-list

readme.md
Also add a ressource website and a Chrome extension upgrading the script.google.com coding experience
=> Add GAS ressources for local development

readme.md
ORM syntax to treat spreadsheet as database table.
On top of background, capabilities to edit notes, background, colours, etc..
Disclaimer: I'm the creator of the library.
=> Added Sheetfu alternative in the ORM section.

readme.md
Added a link to the Google Apps Script starter kit for building GAS projects with next-generation JavaScript.
=> Modern Development Workflow

readme.md
Now I made a new library based on cheerio. Could you add this library your useful list. Thank you.
=> Add cheeriogs

readme.md
Thank you for merging my PR #40 . Sine it was too hard for me to port the library, I made a minimal boilerplate for library developer. This is a description.
In 2018 we have so many boilerplate for google apps script but there are too big for daily scripting or make a trivial library. Sine this issue, I made a new boilerplate depends on webpack only. There are no support for latest EcmaScript spec, just EcmaScript5. In the backend Babel is running but just translating to EcmaScript3.
Thank you!
=> Add gas-minimial-boilerplate

readme.md
Added a separate section for boilerplate and Starter kits for building Apps Script projects locally.
=> Awesome Boilerplates Section

readme.md
The @danthareja/node-google-apps-script project has been deprecated in favour of CLASP and will no longer receive any feature updates or bug fixes.
See [note](https://github.com/danthareja/node-google-apps-script/issues/86#issuecomment-372083316) from the author.
=> Removed deprecated project

readme.md
I think the idea of starter kits by @labnol is great. I've added the TOC and a subhead instead a new header.
=> Modify TOC with new headers

readme.md
The CLASP project was listed twice.
=> Duplicate entry

readme.md
Hi, I added Gexpress which might be useful to people
=> added Gexpress

readme.md
=> Andrew Roberts' resources

readme.md
Hey! Like this list. 
Atlassian open sourced their Gmail add-on, it would be good for people to see the code.
=> Add Atlassian Cloud for Gmail to open source projects list

readme.md
Sheetbase is a platform for developing free websites and apps using GAS, github: https://github.com/sheetbase
=> Add Sheetbase in Utilities

readme.md
Hi Alexander,
Great list!! Wondering if you'll add benlcollins.com to it? I publish tutorials and create online courses around Google Sheets and Apps Script.
Cheers,
Ben
=> Adding a resource to the Apps Script Awesome List

readme.md
Change the Sheetbase homepage url to https://sheetbase.dev
=> Update Sheetbase homepage url

readme.md
Set up a Local Development Environment for Apps Script - https://www.youtube.com/watch?v=KxdCIbeO4Uk
=> Added YouTube Video

readme.md
* A google apps script project using typescript with jest and clasp deploy
* visual studio code debugger works for jest
=> google-app-script-ts-jest

readme.md
Send personalized text messages to contacts with the help of Google Sheets and your Android phone. The SMS messages go directly from your phone SIM, no third-party SMS service is required.
=> SMS Tutorial

readme.md
Hello! Thanks for this very useful list!
I went through some of the links in the Issues and added them to the list:
The changes would close #88, close #89, close #90, close #91, close #93, close #94, close #99, close #102, close #103, close #104, close #105, close #106, close #107, close #109, close #110, close #112, close #114, close #115, close #117, close #119 and close #125.
I also removed http://googlescriptreference.com/, since it seems it's not available anymore.
=> Add new links

readme.md
Signed-off-by: Alex Ivanov <ai@contributor.pw>
=> Clearing. Checking Issues

readme.md
Signed-off-by: Alex Ivanov <ai@contributor.pw>
=> zixia => huan

readme.md
Hi there,
I added my library for unit testing: https://github.com/WildH0g/UnitTestingApp
There is a detailed article about it that I wrote [on Medium](https://medium.com/geekculture/taking-away-the-pain-from-unit-testing-in-google-apps-script-98f2feee281d?source=friends_link&sk=a462104b68e26ccf119c705b205997a6)
I hope you accept the pull request :)
=> Update readme.md with Unit Testing App

readme.md
The backup https://gist.github.com/contributorpw/add04d573c225b3a13b22066be89d085
=> Update formatted tools. Add backups of the tools

readme.md
I created a library that makes `PropertiesStorage` a lot faster by using an in-memory cache. Hopefully it's useful for others too :)
=> Add SpeedStore to Utilities

readme.md
=> feat: add artofthesmart/ob2ss
